#!/usr/bin/env python3
"""Turns a game's table switch to cocktail in MAME 2010, from MAME 2010's own source.

MAME 2010 keeps a game's changed switches in cfg/<game>.cfg as plain XML. The switch is
found in the game's source by its name, Cabinet, along with the port it lives on, its
bit and which value means cocktail. MAME rewrites that file whenever a game quits and
drops anything it did not understand, so after one run the file is read back: if the
setting is still there, MAME took it.

    python3 mame2010_table.py mpatrol pacland ...
"""
import glob, os, re, subprocess, sys

HOME = os.path.expanduser("~")
SRC = HOME + "/.cache/m2010"
CFG = HOME + "/.config/retroarch/saves/MAME 2010/mame2010/cfg"
CORE = HOME + "/.config/retroarch/cores/mame2010_libretro.so"
ENV = dict(os.environ, XDG_RUNTIME_DIR="/run/user/1000", WAYLAND_DISPLAY="wayland-1")
NUM = r"(0x[0-9a-fA-F]+|\d+)"


def sources():
    out = {}
    for p in glob.glob(SRC + "/*/src/mame/drivers/*.c") or glob.glob(SRC + "/*.c"):
        t = open(p, encoding="latin-1").read()
        t = re.sub(r"/\*.*?\*/", " ", t, flags=re.S)
        out[p] = re.sub(r"//[^\n]*", " ", t)
    return out


def block(texts, name):
    for t in texts.values():
        m = re.search(r"INPUT_PORTS_START\(\s*%s\s*\)(.*?)INPUT_PORTS_END" % re.escape(name), t, re.S)
        if m:
            return m.group(1)


def cabinet(game):
    texts = sources()
    ports = None
    for t in texts.values():
        m = re.search(r"GAME\w*\s*\(\s*[\d?]+\s*,\s*%s\s*,\s*\w+\s*,\s*\w+\s*,\s*(\w+)\s*," % re.escape(game), t)
        if m:
            ports = m.group(1)
    if not ports:
        return None
    found = None

    def walk(name):
        nonlocal found
        b = block(texts, name)
        if b is None:
            return
        tag = None
        lines = b.splitlines()
        for n, line in enumerate(lines):
            s = line.strip()
            inc = re.match(r"PORT_INCLUDE\(\s*(\w+)\s*\)", s)
            if inc:
                walk(inc.group(1))
            st = re.match(r'PORT_START\(\s*"([^"]+)"\s*\)', s)
            if st:
                tag = st.group(1)
            d = re.match(r"PORT_DIPNAME\(\s*%s\s*,\s*%s\s*,\s*DEF_STR\(\s*Cabinet\s*\)" % (NUM, NUM), s)
            if d:
                cock = None
                for nxt in lines[n + 1:n + 8]:
                    v = re.match(r"PORT_DIPSETTING\(\s*%s\s*,.*Cocktail" % NUM, nxt.strip())
                    if v:
                        cock = int(v.group(1), 0)
                found = {"tag": tag, "mask": int(d.group(1), 0), "default": int(d.group(2), 0),
                         "cocktail": cock}
    walk(ports)
    return found


def write(game, sw, tag):
    os.makedirs(CFG, exist_ok=True)
    xml = ('<?xml version="1.0"?>\n<mameconfig version="10">\n    <system name="%s">\n'
           '        <input>\n            <port tag="%s" type="DIPSWITCH" mask="%d" defvalue="%d" value="%d" />\n'
           '        </input>\n    </system>\n</mameconfig>\n'
           % (game, tag, sw["mask"], sw["default"], sw["cocktail"]))
    open(os.path.join(CFG, game + ".cfg"), "w").write(xml)


def took(game):
    # MAME writes its "autogenerated" line only when it rewrites the file on the way out;
    # without it the file is just the one written here, and proves nothing
    text = open(os.path.join(CFG, game + ".cfg")).read()
    return "autogenerated" in text and 'type="DIPSWITCH"' in text


def run(path):
    subprocess.run(["timeout", "90", "retroarch", "-L", CORE, path,
                    "--appendconfig=" + HOME + "/demos_raw/headless.cfg", "--max-frames=200"],
                   env=ENV, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def find(stem):
    for p in glob.glob(HOME + "/roms/arcade/**/%s.zip" % stem, recursive=True):
        if "/mamesets/" not in p:
            return p


LOG = HOME + "/flip_raw/m2010_log.txt"


def log(msg):
    import time
    with open(LOG, "a") as f:
        f.write(time.strftime("%H:%M:%S ") + msg + chr(10))


def one(g):
    """Start it, set the table switch, confirm MAME took it, film two players."""
    import time
    path = find(g)
    if not path:
        log("NO FILE  %-10s" % g); return
    sw = cabinet(g)
    if not sw or sw["cocktail"] is None:
        log("NO SWITCH %-10s %s" % (g, sw)); return
    result = None
    for tag in (sw["tag"], ":" + sw["tag"]):
        write(g, sw, tag)
        run(path)
        if os.path.exists(os.path.join(CFG, g + ".cfg")) and took(g):
            result = tag
            break
    if not result:
        log("NOT RUN  %-10s MAME 2010 did not start it, or refused the switch" % g); return
    t0 = time.time()
    subprocess.run(["python3", HOME + "/fliptest_one.py", g, os.environ.get("MT_PORT", "57000"), "mame2010"],
                   cwd=HOME, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    ok = os.path.exists("%s/flip_raw/%s_m2010.mkv" % (HOME, g))
    log("%s %-10s tag %s, %.0f s" % ("filmed  " if ok else "NO FILM ", g, result, time.time() - t0))


if __name__ == "__main__" and len(sys.argv) > 1 and sys.argv[1] == "--all":
    for g in sys.argv[2:]:
        if os.path.exists("%s/flip_raw/%s_m2010.mkv" % (HOME, g)):
            continue
        try:
            one(g)
        except Exception as ex:
            log("ERROR    %-10s %s" % (g, str(ex)[:80]))
    log("FINISHED")
    sys.exit(0)

if __name__ == "__main__":
    for g in sys.argv[1:]:
        sw = cabinet(g)
        if not sw or sw["cocktail"] is None:
            print(g, "no table switch found", sw)
            continue
        result = None
        # MAME 2010 names ports either plainly or with a leading colon; try both
        for tag in (sw["tag"], ":" + sw["tag"]):
            write(g, sw, tag)
            run(find(g))
            if took(g):
                result = tag
                break
        print(g, sw, "TOOK with tag %s" % result if result else "NOT TAKEN")
